android.enableJetifier=true
android.useAndroidX=true
org.gradle.jvmargs=-Xmx8192m

# Versioning
VERSION_NAME=1.7.0
VERSION_CODE=12
APP_ID=org.fossify.musicplayer
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
android.builtInKotlin=false
android.newDsl=false
